In [11]:
import numpy as np

def sigmoid(x):
	return 1.0/(1.0 + np.exp(-x))

def sigmoid_der(x):
	return x*(1.0 - x)

class NN:
    def __init__(self, inputs, outputs, it):
        self.inputs = inputs
        self.lenght=len(self.inputs)
        print(self.lenght)
        self.lenght_inputs=len(self.inputs[0])
        print(self.lenght_inputs)
        self.it = it
        self.outputs = outputs
        
        self.wi=np.random.random((self.lenght_inputs, self.lenght))
        print(self.wi)
        self.wh=np.random.random((self.lenght, 1))
        print(self.wh)
        self.train()

    def think(self, X):
        s1=sigmoid(np.dot(X, self.wi))
        s2=sigmoid(np.dot(s1, self.wh))
        return s2

    def train(self):
        for i in range(self.it):
            l0=self.inputs
            l1=sigmoid(np.dot(l0, self.wi))
            l2=sigmoid(np.dot(l1, self.wh))

            l2_err=self.outputs - l2
            l2_delta = np.multiply(l2_err, sigmoid_der(l2))

            l1_err=np.dot(l2_delta, self.wh.T)
            l1_delta=np.multiply(l1_err, sigmoid_der(l1))

            self.wh+=np.dot(l1.T, l2_delta)
            self.wi+=np.dot(l0.T, l1_delta)

In [12]:
X=np.array([[0,0], [0,1], [1,0], [1,1] ]) # Entradas
D=np.array([[0],[1],[1],[0] ]) # Salidas deseadas

n=NN(X, D, 10000)
n.think(inputs)

4
2
[[0.6678141  0.37782884 0.69441251 0.79430183]
 [0.92774689 0.95048091 0.63025742 0.11741881]]
[[0.09602547]
 [0.24185038]
 [0.97638144]
 [0.52672368]]


array([[0.02611329],
       [0.98100244],
       [0.98181618],
       [0.01224575]])

In [18]:
np.dot(X,qq)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.92774689, 0.95048091, 0.63025742, 0.11741881],
       [0.6678141 , 0.37782884, 0.69441251, 0.79430183],
       [1.59556099, 1.32830975, 1.32466993, 0.91172064]])

In [13]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [17]:
qq = np.array([[0.6678141,0.37782884,0.69441251,0.79430183],[0.92774689,0.95048091,0.63025742,0.11741881]])
qq

array([[0.6678141 , 0.37782884, 0.69441251, 0.79430183],
       [0.92774689, 0.95048091, 0.63025742, 0.11741881]])